services:
  crunchy:
    image: ${CRUNCHY_IMAGE:-ghcr.io/avnogy/crunchy:latest}
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    env_file:
      - .env
    volumes:
      # Persist app settings.
      - ./config:/config
      # Store completed downloads.
      - ./output:${OUTPUT_DIR:-/data/output}
    tmpfs:
      - ${TRANSCODING_TEMP_DIR:-/data/temp}:rw,size=4g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
